inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'coverage/**/*'
    - 'log/**/*'
    - 'node_modules/**/*'

Metrics/LineLength:
  Max: 93
