AllCops:
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'coverage/**/*'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'app/controllers/application_controller.rb'
    - 'app/jobs/application_job.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'app/channels/application_cable/channel.rb'
    - 'app/channels/application_cable/connection.rb'

Metrics/LineLength:
  Max: 93

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/NumericLiterals:
  Enabled: false
