language: ruby
sudo: false

addons:
  postgresql: "9.4"

before_install:
  - gem install bundler

env:
  - DB=postgresql

before_script:
  - psql -c 'create database mtg_app_test' -U postgres

script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate
  - RAILS_ENV=test bundle exec rspec
