language: ruby
sudo: false

branches:
  only:
    - master

addons:
  postgresql: "9.4"

env:
  - DB=postgresql

before_script:
  - psql -c 'create database mtg_app_test' -U postgres

script:
  - npm install
  - RAILS_ENV=test bundle exec rake --trace db:migrate
  - RAILS_ENV=test bundle exec rspec
